language: python
dist: xenial
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  # Validate all YAML files in the directory
  - |
    if [ $SPHINX_VERSION = dev ] ; then
        find . -type f -name '*.yml' -print0 | xargs -0 -i python -c "import yaml ; yaml.safe_load(open('{}'))" || exit 1
    else
        true
    fi
  # Build the project
  - make data.json
